### ISSUE TITLE
Model data > JSON Table Schema + OS Data Package

### ISSUE THREAD

**Issue by pwalsh** [openspending/etlcli-mvp#2]
(See the [README for overview of the flow](https://github.com/openspending/etlcli-mvp#flow), this being Step 2.)

The user of the ETL CLI has a CSV of data, and has already [ensured the data source is well formed](https://github.com/openspending/etlcli-mvp#step-1-ensure-resources-are-well-formed). Next, the user needs to model this data, with the end result being a data package that is ready for upload to the OS Datastore.

## Tasks

* [x] New CLI for this step (`osmodel`)
* [x] Infer schema (using [jtskit](https://github.com/okfn/jtskit-py))
* [x] Infer or accept mapping of the minimum required fields (user can pass a mapping to the CLI)
    * fail of not minimum requirements: e.g.: id
* [x] Create a OS Budget data package
* [x] write it all into a local destination in data package format
    * [x] write data package descriptor
    * [x] write all data/*
    * [x] write all archive/*

**Comment by pwalsh** [comment]
## Some additions

* [ ] Resource name (filename without extension for now)
* [ ] Currency as required on budget data package
